name: ezil_agency
description: "ezil agency"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-174.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # ICONS
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # STATE MANAGEMENT
  get: ^4.6.6

  # UTILITY
  readmore: ^2.2.0
  lottie: ^2.7.0
  animated_text_kit: ^4.2.2
  widget_and_text_animator: ^1.1.5
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/logos/
    - assets/animations/
    - assets/icons/
    - assets/icons/languages/
    - assets/images/mobile_app/
    - assets/images/web_app/
    - assets/images/web_site/

  fonts:
    - family: San
      fonts:
        - asset: assets/fonts/san_medium.otf
    - family: Vip
      fonts:
        - asset: assets/fonts/Vipsanie.otf
    - family: Cal
      fonts:
        - asset: assets/fonts/Cal.otf

